language: java
jdk: openjdk11
os: linux
dist: trusty
script: 
  - ./gradlew check
  - ./gradlew sonarqube
  - ./gradlew buildDocker

deploy:
  provider: gae
  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
  project: enduring-honor-256422

